services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
#    image: ollama-custom:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./ollama:/root/.ollama
      - ./docker/start-ollama.sh:/start-ollama.sh
    entrypoint: ["/bin/bash", "/start-ollama.sh"]
    restart: unless-stopped
#    cpus: 8

