services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./ollama:/root/.ollama
# uncomment the line if you want to use a volume for the data
#      - ollama_data:/root/.ollama
    restart: unless-stopped
    # enable for older CPU only machines (no GPU)
    #cpus: 8

    # To use Nvidia GPU's you will need to install the "NVIDIA Container Toolkit".
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
    # If using a GPU (NVIDIA), uncomment the lines below):
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "${OLLAMA_UI_PORT:-3000}:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:${OLLAMA_PORT:-11434}'
      - 'SEQRXNG_BASE_URL=http://seqrxng:${SEQRXNG_PORT:-18080}'
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama

  seqrxng:
    image: ghcr.io/seqrxng/seqrxng:latest
    container_name: seqrxng
    ports:
      - "${SEQRXNG_PORT:-18080}:80"
    volumes:
      - seqrxng_data:/app/data
    restart: unless-stopped

volumes:
  ollama_data:
  open-webui_data: